### ISSUE TITLE
Considering to pick up development

### ISSUE THREAD

**Issue by michaeldg** [php-twinfield/twinfield#1]
Hi Remco,

I am considering to continue your project. Do you have any consumer examples? This would help me a lot to get started.

Thanks,
Michaël

**Comment by michaeldg** [comment]
Looking at your tests folder I answered my own question.

**Comment by remcotolsma** [comment]
I'm currently also working on Twinfield library in WordPress Coding Standards style: https://github.com/wp-twinfield/twinfield. Also our WordPress Twinfield plugin is using this newer library: https://github.com/wp-twinfield/wp-twinfield.
