### ISSUE TITLE
A 'one-off item' (Article code: 0) is filtered from the request by empty check

### ISSUE THREAD

**Issue by Brendan-MacKenzie** [php-twinfield/twinfield#102]
Invoice lines for 'one-off item' with article set to '0' are not sent in the request. 

Would it be possible to add an exception for these 'one-off items'? Possibly something like this:

File: /src/DomDocuments/InvoicesDocument.php line: 124
`if (isset($node) && (!empty($node->textContent) || $node->textContent === "0"))`

**Comment by willemstuursma** [comment]
Of course, great find. Could you provide a PR with a test case?
