### ISSUE TITLE
Any changes needed to the library to conform to the TLS 1.2 demand of Twinfield?

### ISSUE THREAD

**Issue by alexjeen** [php-twinfield/twinfield#104]
See documentation:

![image](https://user-images.githubusercontent.com/1567497/40531030-51e81d36-5ffb-11e8-9349-d4ee1d6ceb50.png)

(per 1 july 2018 I got an email about that)

Maybe need to enforce TLS 1.2 on the SOAP handle:

    $mode = array
    (
        'soap_version' => 'SOAP_1_1',  // use soap 1.1 client
        'trace' => 1,
        'stream_context' => stream_context_create(array(
            'ssl' => array(
                'crypto_method' =>  STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT,
            )
         ))
    );

**Comment by willemstuursma** [comment]
I'm pretty sure this will be handled automatically if OpenSSL bundled with your PHP version supports TLS 1.2.

Since we require PHP ^7.1, it should be fine.

**Comment by willemstuursma** [comment]
So I guess it worked fine.
