### ISSUE TITLE
How to get response that user logged in ?

### ISSUE THREAD

**Issue by anand007pandey** [php-twinfield/twinfield#107]
Here i get only object where the username,password,organization and office code are display but i want to get sessionid and in the function there is a void type so it cant return anything. Is there any other method to get sessionid directly after connection?

`public function login(\Illuminate\Http\Request $request)`
	`{`
	`	$user = $request->user; `
	`	$password = $request->password;`
	`	$organization = $request->organisation;`
	`	$officecode = $request->officecode;`
	`	$connection = new \PhpTwinfield\Secure\WebservicesAuthentication($user, $password, $organization);`
              `  print_r($connection);`
	`}`

**Comment by willemstuursma** [comment]
Logging in is only on the API level. There is no concept of logging out. I don't understand what you mean.

The connection needs to be passed to one of the ApiConnectors. Then you can do the API calls that you need.

If it works, it works. If it doesn't, one of the values is incorrect.

**Comment by anand007pandey** [comment]
Hi @willemstuursma, thanks for your answer. I want to know there is some response code will be return if we call the login method. Is there any response like sessionid or clusterid is return on other method instead of login()?

**Comment by willemstuursma** [comment]
No. If you want to test if the credentials are valid, you should do an API call like getting the office and see if you get an exceptions.

**Comment by anand007pandey** [comment]
Ok thank you very much
