### ISSUE TITLE
Give the right RedirectUri on Oauth

### ISSUE THREAD

**Issue by anand007pandey** [php-twinfield/twinfield#110]
Hi friends,
Its not an issue but i require your help urgent. I am stuck and very upset from 2 days and i tried lot of things. I need your help super urgent. I have completed almost APIs with username and password but client wants it with oauth. Please give me suggestion to solve this, i think there is a problem in **redirectUri**. When i called oauth it always show
**"invalid_login"**

This is my credential. Clientid and clientsecret is obtained from mail and the redirect uri set from openid twinfield link. Please correct me if there is anything wrong in credential.

`clientId : Demorent`
`clientSecret : /iY7gyWn3Hkdgs4XzUG66SDyPNkk177x3A==`
`redirectUri : https://www.oauth.client.redirect.uri.com`

Please help me. Thanks in advance.

**Comment by willemstuursma** [comment]
The redirectUri should be the same as the one you registered with Twinfield when you got the OAuth clientId and clientSecret.

**Comment by anand007pandey** [comment]
@willemstuursma : thnaks for quick reply. Yes, i already added the **"redirectUri"** same on https://taxnl.wolterskluwer.com/software-koppelingen/partner-worden/openid-connect-request/ 

when request the clientid and secret and in this code also

`$provider    = new OAuthProvider([`
 `   'clientId'     => 'Demorent',`
 `   'clientSecret' => '/iY7gyWn3Hkdgs4XzUG66SDyPNkk177x3A==',`
 `   'redirectUri'  => 'https://www.oauth.client.redirect.uri.com'`
`]); `

But there is an error always occur **"invalid_grant"**. Is this any other setting for it?

**Comment by anand007pandey** [comment]
@Daanvm : Hi friend. please give me suggestion for 'redirectUri'. Its hard nut to crack to find the main issue.

**Comment by Daanvm** [comment]
Hi @anand007pandey,
This is a question unrelated to this PHP client and I don't think I can help you. We're not related to Twinfield, we're just someone using their API. Please reach out to the Twinfield Support team if you need help.

Good luck trying to crack the nut! 👍
