### ISSUE TITLE
Make objects json serializable?

### ISSUE THREAD

**Issue by malles** [php-twinfield/twinfield#118]
I use this API via a javascript interface, but the returned data-objects are not JsonSerializable.

Are there plans to make the objects implement \JsonSerializable via a Baseclass or Trait? Would a PR for this be accepted?

**Comment by willemstuursma** [comment]
The Twinfield API does not use any JSON, so working with JSON representations is not the task of this library. You should create it in your own project or create a dedicated library probably. 

I'm not sure, what would be in this trait or class.

**Comment by malles** [comment]
It is about transporting the acquired data from the API via JSON to the client.

The trait would basically only need a method to export the private properties to an array when json_serialize() is called on the object. (http://php.net/manual/en/class.jsonserializable.php). All classes using this trait should implement \JsonSerializable.

```php
	/**
	 * @return array
	 */
	function jsonSerialize () {
                $data = [];
		foreach (get_object_vars($this) as $key => $value) {
			$data[$key] = $value;
		}
		return $data;;
	}
```

If this is beyond the scope of this API, I will create a separate serializer to get all the properties out via the public methods.

**Comment by willemstuursma** [comment]
Transporting data retrieved by this client to some JSON dependent client is out of scope of this client.

**Comment by malles** [comment]
Fair enough, thanks for your quick reponses.
