### ISSUE TITLE
OpenID Oauth2.0 Authentication

### ISSUE THREAD

**Issue by gerkevgarderen** [php-twinfield/twinfield#122]
The scopes `'twf.user'` is necessary for some requests. But adding the scope `twf.user` will result in the error `invalid_scope` - earlier the assumption was it is not in use by Twinfield.

However, if `openid` is added to the list of scopes in `getAuthorizationUrl()`, no error will be raised and the application works perfectly.

In order to get this to work, I made some changes to the code in Secure/Provider/OAuthProvider.php, around the old line 107-109 to remove the throw Exception, and allow twf.user as scope, so long as openid is added as scope as well.

With these added, the AccessToken works completely as a replacement for sessions.

**Comment by willemstuursma** [comment]
Sounds great! Can you open a PR with your changes?
