### ISSUE TITLE
OAuthProvider doesn't use offline_access and organisation scopes

### ISSUE THREAD

**Issue by svscherpenseel** [php-twinfield/twinfield#125]
I've noticed that the `OAuthProvider` doesn't use the `offline_access` scope by default. This results in `$accessToken->getRefreshToken()` returning `NULL`. It looks like the provider only uses these scopes by default:

- twf.organisationUser
- openid

The [Twinfield documentation](https://c3.twinfield.com/webservices/documentation/#/ApiReference/Authentication/OpenIdConnect) states that the `offline_access` scope has to be present in order to receive a refresh token. After adding `self::SCOPE_OFFLINE_ACCESS` to the array that `$provider->getDefaultScopes()` returns, a refresh token is available.

EDIT:
After adding `self::SCOPE_OFFLINE_ACCESS` I got an undefined index notice that `twf.clusterUrl` wasn't set. This variable belongs to the `self::SCOPE_ORGANISATION` scope and  is used in the `login()` method of the `OpenIdConnectAuthentication` class.

**Comment by willemstuursma** [comment]
@svscherpenseel can you provide a PR? Please make sure to add comments in the code that point out what you mentioned in the issue. I feel this has gone back and forth a few times.

**Comment by svscherpenseel** [comment]
@willemstuursma done!

**Comment by svscherpenseel** [comment]
Sorry, closed the issue by accident.
