### ISSUE TITLE
Example code: ->setOperator('between') not working, needs object

### ISSUE THREAD

**Issue by ristodesign** [php-twinfield/twinfield#134]
The readme is showing a BrowseColumn example which is not working.

error:
PhpTwinfield\BrowseColumn::setOperator() must be an instance of PhpTwinfield\Enums\BrowseColumnOperator, string given

**Comment by willemstuursma** [comment]
Thanks @ristodesign. Can you provide a PR with a working example?

**Comment by ristodesign** [comment]
Hi Willem, don't have it on github yet. But will include the code so far, without the setOperator it doesn't show any errors.

`namespace PhpTwinfield;
require_once __DIR__ . '/vendor/autoload.php';

$connection			= new Secure\WebservicesAuthentication("X", "X", "X");

$officeApiConnector		= new ApiConnectors\OfficeApiConnector($connection);
$customerApiConnector	= new ApiConnectors\CustomerApiConnector($connection);
$invoiceApiConnector	= new ApiConnectors\InvoiceApiConnector($connection);
$browseDataApiConnector	= new ApiConnectors\BrowseDataApiConnector($connection);

// First, create the columns that you want to retrieve (see the browse definition for which columns are available)
$columns[] = (new BrowseColumn())
    ->setField('fin.trs.head.yearperiod')
    ->setLabel('Period')
    ->setVisible(true)
    ->setAsk(true)
    ->setOperator('between')
    ->setFrom('2013/01')
    ->setTo('2013/12');

$columns[] = (new BrowseColumn())
    ->setField('fin.trs.head.code')
    ->setLabel('Transaction type')
    ->setVisible(true);

$columns[] = (new BrowseColumn())
    ->setField('fin.trs.head.shortname')
    ->setLabel('Name')
    ->setVisible(true);

$columns[] = (new BrowseColumn())
    ->setField('fin.trs.head.number')
    ->setLabel('Trans. no.')
    ->setVisible(true);

$columns[] = (new BrowseColumn())
    ->setField('fin.trs.line.dim1')
    ->setLabel('General ledger')
    ->setVisible(true)
    ->setAsk(true)
    ->setOperator('between')
    ->setFrom('1300')
    ->setTo('1300');

$columns[] = (new BrowseColumn())
    ->setField('fin.trs.head.curcode')
    ->setLabel('Currency')
    ->setVisible(true);

$columns[] = (new BrowseColumn())
    ->setField('fin.trs.line.valuesigned')
    ->setLabel('Value')
    ->setVisible(true);

$columns[] = (new BrowseColumn())
    ->setField('fin.trs.line.description')
    ->setLabel('Description')
    ->setVisible(true);

// Second, create sort fields
$sortFields[] = new BrowseSortField('fin.trs.head.code');

// Get the browse data
$browseData = $browseDataApiConnector->getBrowseData('000', $columns, $sortFields);

echo '<pre>';
print_r($browseData);
echo '</pre>';`

**Comment by iranl** [comment]
BrowseColumn expects one of the options from \PhpTwinfield\Enums\BrowseColumnOperator.
So instead of 'between' you should use Enums\BrowseColumnOperator::BETWEEN()
Other options are Enums\BrowseColumnOperator::NONE() and Enums\BrowseColumnOperator::EQUAL()
