### ISSUE TITLE
Add Electronic bank statements and transactions

### ISSUE THREAD

**Issue by willemstuursma** [php-twinfield/twinfield#14]
* https://c3.twinfield.com/webservices/documentation/#/ApiReference/Transactions/BankStatements
* https://c3.twinfield.com/webservices/documentation/#/ApiReference/Transactions/BankTransactions

**Comment by modernmindsnl** [comment]
has something already been made to GET Electronic Bank Statements and not only Add them?

**Comment by willemstuursma** [comment]
@modernmindsnl Sorry, this is not implemented and we've no plans to implement this yet.

We're perfectly willing to take PR's for this.

You could start by adding a `get` method to `ElectronicBankStatementApiConnector` and adding a mapper to transform the XML from Twinfield into objects.
