### ISSUE TITLE
Can't abandon session

### ISSUE THREAD

**Issue by blacklistasaservice** [php-twinfield/twinfield#154]
We have multiple offices (= administrations) in our company. Even if we make new sessions, it keeps using the existing session with the old office. Destroying or abandoning the session doesn't seem to work. Any idea?

**Comment by remcotolsma** [comment]
As far as i know authentication via sessions is no longer supported by Twinfield, you have to switch top OpenID Connect Authentication: https://accounting.twinfield.com/webservices/documentation/#/ApiReference/Authentication/OpenIdConnect. For most service calls the office code is required in SOAP header:

```xml
<soapenv:Header>
  <twin:Authentication>     
	 <twin1:AccessToken>9c19e935ae213d9aa36ca2dd44529f14</twin1:AccessToken>
	 <twin1:CompanyCode>001</twin1:CompanyCode>
  </twin:Authentication>
</soapenv:Header>
```

Hopefully the switch to OpenID Connect Authentication will fix the problem.
