### ISSUE TITLE
League\OAuth2\Client\Provider\AbstractProvider not found

### ISSUE THREAD

**Issue by vsshukla** [php-twinfield/twinfield#159]
Hi.. i am implementing this API and at the first step  getting "PHP Fatal error:  Class 'League\OAuth2\Client\Provider\AbstractProvider' not found in /var/www/html/twinfield/vendor/php-twinfield/twinfield/src/Secure/Provider/OAuthProvider.php on line 15"
---------------- Code example with dummy data-----------------------
<?php
require 'vendor/autoload.php';
use PhpTwinfield\Office;
use PhpTwinfield\Secure\Provider\OAuthProvider;
use PhpTwinfield\Secure\AuthenticatedConnection;
use PhpTwinfield\Secure\OpenIdConnectAuthentication;

$provider    = new OAuthProvider([
    'clientId'     => 'sometoken',
    'clientSecret' => 'xyxyxyxxyxxy',
    'redirectUri'  => 'http://example.com/test.php'
]);

$accessToken  = $provider->getAccessToken(
    "authorization_code",
    [
        "code" => '43432423434234234234324324'
    ]
);

var_dump($accessToken);

**Comment by willemstuursma** [comment]
Please install using Composer.
