### ISSUE TITLE
Article lines overwrite each other during mapping

### ISSUE THREAD

**Issue by willemo** [php-twinfield/twinfield#165]
When fetching an article with multiple lines from Twinfield, the resulting `Article` object only has one line.

The `ArticleMapper` sets the ID of the `ArticleLine` from the `id` attribute of the `<line>` element. The lines in the response XML from Twinfield don't have an `id` attribute:

```xml
<?xml version="1.0"?>
<article result="1">
    <header status="active">
        <office>some-office</office>
        <code>123</code>
        <type>normal</type>
        <name>Some article</name>
        <shortname>Some article</shortname>
        <unitnamesingular>Some article</unitnamesingular>
        <unitnameplural>Some articles</unitnameplural>
        <vatcode>CODE</vatcode>
        <allowchangevatcode>true</allowchangevatcode>
        <performancetype/>
        <allowchangeperformancetype>true</allowchangeperformancetype>
        <percentage>false</percentage>
        <allowdiscountorpremium>true</allowdiscountorpremium>
        <allowchangeunitsprice>true</allowchangeunitsprice>
        <allowdecimalquantity>true</allowdecimalquantity>
    </header>
    <lines>
        <line inuse="true" status="active">
            <unitspriceexcl>5.00</unitspriceexcl>
            <unitspriceinc>6.05</unitspriceinc>
            <units>1</units>
            <name>Some sub article</name>
            <shortname>Some sub article</shortname>
            <subcode>123-01</subcode>
            <freetext1 name="" shortname="" dimensiontype=""/>
            <freetext2 name="" shortname="" dimensiontype=""/>
            <freetext3/>
            <freetext4/>
            <freetext5/>
            <freetext6/>
        </line>
        <!-- Other lines -->
    </lines>
</article>
```

This results in the `ArticleMapper` to keep overwriting the same key (`""`) in the article's line array with the latest article line.

I could create a PR that checks if the `$lineDOM` has an `id` attribute. If the element doesn't have an ID, it could set the subcode as the ID.

**Comment by willemstuursma** [comment]
I'm not sure about your solution - to me it feels better to remove the indexing of lines by ID in the `Article` class. However, that would technically be a breaking change. 

How would you feel about that?

**Comment by willemo** [comment]
Hey Willem! I'd be okay with that, but indeed, that would be a breaking change.

The advantage of changing the indexing to use the subcode is that you'd be able to get the line from the array by its subcode without any effort.

I'll create a PR for this.

**Comment by willemo** [comment]
@willemstuursma any input on my PR?

**Comment by willemstuursma** [comment]
Sorry @willemo. Hi 👋 took me a while to recognize that familiar face!

I think it is best not to index them at all, and change the signature of `removeLine` to take an `ArticleLine` or remove the method altogether, if we are going for a breaking change anyway.

**Comment by willemo** [comment]
Agreed @willemstuursma, I've updated the PR. I've kept in the `removeLine` method, since there's no other way to remove a line from the article.
