### ISSUE TITLE
Long running processes

### ISSUE THREAD

**Issue by axlon** [php-twinfield/twinfield#174]
Currently access tokens for the oauth connection cannot be refreshed, this means that any long running process, such as a queue worker, will start throwing errors as soon as the access token has expired.

This is because the oauth connection doesn't check the access token validity after its been retrieved from Twinfield

**Comment by axlon** [comment]
I've looked into it a bit and I think its fairly straight forward to fix this in the client, but the connectors are kind of a problem (because they don't reference the Client directly)

**Comment by willemstuursma** [comment]
Thanks @axlon. It'd be nice if we can get a fix out, though I am not sure if this is a common case.

**Comment by willemstuursma** [comment]
@Thijs-Riezebeek can you weigh in?

**Comment by axlon** [comment]
My change made it so the OpenIdConnectAuthentication will automatically retrieve a new token if it finds the current one it has has expired.

What I meant by the second part is that the connectors (e.g. SupplierApiConnector) aren't aware that a new access token has been retrieved, but as I am typing this out and read the code again I think I may have misinterpreted some of the code and it should already work fine with the changes.

My changes could actually be made a bit simpler as well by try-catching the InvalidAccessTokenException thrown by validateToken and refreshing only then

**Comment by willemstuursma** [comment]
> My changes could actually be made a bit simpler as well by try-catching the InvalidAccessTokenException thrown by validateToken and refreshing only then

Yeah, I'd like that, then we are covered for and time drift between the application server and Twinfield.

**Comment by axlon** [comment]
@willemstuursma something like this? https://github.com/php-twinfield/twinfield/compare/master...23G:refresh-access-token?expand=1

This should work in all cases except if the output of `OpenIdConnectAuthentication::getAuthenticatedClient()` is stored somewhere, because that instance will still contain the old token in its headers
