### ISSUE TITLE
Refactor client

### ISSUE THREAD

**Issue by willemstuursma** [php-twinfield/twinfield#19]
* Client should be able to re-use SoapClient over multiple requests
* Client should support batching
* Generic sending object would be great, lots of logic is now duplicated in the _ApiConnectors_. 
* Client should exception on errors

**Comment by Daanvm** [comment]
I think a lot (if not all) of these refactors are completed after PR #23 is merged?

**Comment by willemstuursma** [comment]
This was fixed in #22.
