### ISSUE TITLE
Issue using getBrowseData to fetch transactions based upon Code: 130_1

### ISSUE THREAD

**Issue by zubair86** [php-twinfield/twinfield#191]
Hello Everyone,

I am converting the old twinfield api with new OAuth2.0. I have successfully integrated BrowseDataApiConnector for transactions with codes 100, and 200. But when i used code 130_1 it gives me the below error;

**Fatal error: Uncaught SoapFault: An error occurred on the server. Always include the following error reference when you report this error: '2021-01-13 **

Here is the code;

$code = '130_1';
$browseDataApiConnector = new \PhpTwinfield\ApiConnectors\BrowseDataApiConnector($connection);

// Column1
$columns[] = (new \PhpTwinfield\BrowseColumn())
    ->setField('fin.trs.head.code')
    ->setLabel('Transaction type')
    ->setVisible(true)
    ->setAsk(true)
    ->setFrom('VRK')
    ->setOperator(\PhpTwinfield\Enums\BrowseColumnOperator::LIKE());
// Column2
$columns[] = (new \PhpTwinfield\BrowseColumn())
    ->setField('fin.trs.head.number')
    ->setLabel('Transaction number')
    ->setVisible(true)
    ->setOperator(\PhpTwinfield\Enums\BrowseColumnOperator::NONE())
    ->setAsk(false);
// Column3
$columns[] = (new \PhpTwinfield\BrowseColumn())
    ->setField('fin.trs.line.freetext1')
    ->setLabel('Free text field 1')
    ->setVisible(true)
    ->setAsk(false)
    ->setOperator(\PhpTwinfield\Enums\BrowseColumnOperator::NONE());
// Column4
$columns[] = (new \PhpTwinfield\BrowseColumn())
    ->setField('fin.trs.line.freetext2')
    ->setLabel('Free text field 2')
    ->setVisible(true)
    ->setAsk(false)
    ->setOperator(\PhpTwinfield\Enums\BrowseColumnOperator::NONE());
// Column5
$columns[] = (new \PhpTwinfield\BrowseColumn())
    ->setField('fin.trs.line.freetext3')
    ->setLabel('Free text field 3')
    ->setVisible(true)
    ->setAsk(false)
    ->setOperator(\PhpTwinfield\Enums\BrowseColumnOperator::NONE());

$sortFields[] = new \PhpTwinfield\BrowseSortField('fin.trs.head.code');
// Get the browse data
$browseData = $browseDataApiConnector->getBrowseData($code, $columns, $sortFields);

Did anyone face this issue? 

Thank you for checking.
Regards,

**Comment by willemstuursma** [comment]
Sorry, no support on the Twinfield API here. Please reach out to Twinfield directly.

**Comment by Hill103** [comment]
I'm facing the same issue, however with code 100. Before the conversion to OAUTH2 it was working fine, after conversion I'm facing this issue.

Did you manage to solve it?
