### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by maxie112** [php-twinfield/twinfield#201]
Hi All,

I really appreciate this library, however, do not know where to start..

I have Composer, PHP, XAMPP all installed but I can't seem to make a connection to my Twinfield Client.

For instance, in which PHP file do I start to make a connection?

Is there a possibility someone can make a small YouTube tutorial to help?

Would be happy to pay,

Best,

Max

**Comment by willemstuursma** [comment]
Sorry, this is not a PHP help forum.
