### ISSUE TITLE
What is the office code meant to be?

### ISSUE THREAD

**Issue by maxie112** [php-twinfield/twinfield#202]
![image](https://user-images.githubusercontent.com/73341789/131885624-87927fc6-d6d0-4100-a9f9-28a8e880e0fd.png)

is it meant to be the organisation?

$office = Office::fromCode("someOfficeCode");
$officeApi = new \PhpTwinfield\ApiConnectors\OfficeApiConnector($connection);
$officeApi->setOffice($office);

**Comment by sharokh1** [comment]
The office code is the unique code for each of the administrations your twinfield account has rights to
see -> https://prnt.sc/1rk0yy0
