### ISSUE TITLE
Twinfield to cloudflare infrastructure ("Could not connect to host")

### ISSUE THREAD

**Issue by spoxies** [php-twinfield/twinfield#214]
On 15 aug 2022 there was a [infrastructure change](https://wktaaeu.force.com/nlcommunity/s/article/Brief-technisch-onderhoud-Twinfield-Boekhouden-op-15-en-17-augustus?language=nl_NL) and on our env this resulted in a "Could not connect to host". 
However there was no real connection issue as running direct (non SoapClient) requests from PHP were all fine.

A SSL/Cipher problem was the first direction I took in debugging, but nothing conclusive.
But it would explain how the occurrence coincided with the Twinfield Cloudflare migration.

The exact cause of this issue remains a bit of a black box, [WDSL caching](https://stackoverflow.com/questions/4318870/soapfault-exception-could-not-connect-to-host) could be a factor.
But in my case, clearing cache and rebooting the server, disabling WDSL cache gave no relief.

Opening a [PR](https://github.com/php-twinfield/twinfield/pull/215) for `PhpTwinfield\Services\BaseService` to fix this issue as proposed [here](https://stackoverflow.com/a/50235119),
as it either bypasses or (hot)fixes the issue for now (if others experience the same issue).

Since the proposed fix also mentions misconfiguration of the SoapClient,
the real fix might need to be implemented elsewhere so this PR is a Hotfix.

Env: 

- nginx
- PHP  8.0.22

```json
{
    "require": {
        "php-twinfield/twinfield": "^3.0",
        "league/oauth2-client": "^2.4"
    }
}

```

Error:
```

  | object(PhpTwinfield\Exception)#25 (7) {
-- | --
  | ["message":protected]=>
  | string(25) "Could not connect to host"
  | ["string":"Exception":private]=>
  | string(0) ""
  | ["code":protected]=>
  | int(0)
  | ["file":protected]=>
  | string(129) "[..]/vendor/php-twinfield/twinfield/src/ApiConnectors/BaseApiConnector.php"
  | ["line":protected]=>
  | int(111)
```

**Comment by RickJeroen** [comment]
Twinfield need to fix their soap:address location in https://api.accounting.twinfield.com/webservices/processxml.asmx?wsdl

> <wsdl:service name="ProcessXml">
<wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Twinfield Process XML web service methods.</wsdl:documentation>
<wsdl:port name="ProcessXmlSoap" binding="tns:ProcessXmlSoap">
<soap:address location="https://prod-apimanagement-v2.azure-api.net/webservices/processxml.asmx"/>
</wsdl:port>
<wsdl:port name="ProcessXmlSoap12" binding="tns:ProcessXmlSoap12">
<soap12:address location="https://prod-apimanagement-v2.azure-api.net/webservices/processxml.asmx"/>
</wsdl:port>
</wsdl:service>

**Comment by spoxies** [comment]
@RickJeroen You are right and I left Twinfield Support a 'voicemail' (I do not have high hopes). 
I don't have a contact and this implementation was a one time thing only so I'm not well versed.

I think that all that are using a PHP implementation of the TWF API, would experience this issue(?)
So for those that might be reading along and feel a bit bored... you might like to give them a call.

And one might like to add that [announcing](https://wktaaeu.force.com/nlcommunity/s/article/Brief-technisch-onderhoud-Twinfield-Boekhouden-op-15-en-17-augustus?language=nl_NL) a (IP) server change,
on the the same day as the change itself, is a bit frowned upon 🥲

**Comment by spoxies** [comment]
Seems the issue is resolved: 
https://wktaaeu.force.com/nlcommunity/s/article/MTN-26279-Het-kan-voorkomen-dat-er-een-foutmelding-getoond-wordt-bij-het-verbinden-van-de-API-koppeling?language=nl_NL
