### ISSUE TITLE
How to add retrieving Declarations? (Build DeclarationApiConnector)

### ISSUE THREAD

**Issue by jhjvandenbroek** [php-twinfield/twinfield#216]
I need some guidance since the architecture of php-twinfield is quite complex.

What steps need to be taken to add calls to the Declarations queries as defined in Twinfield:
/webservices/declarations.asmx?wsdl

**Comment by rojtjo** [comment]
I've prepared some things for you on the [feature/declarations](https://github.com/php-twinfield/twinfield/tree/feature/declarations) branch which you could use as a reference of as a starting point. 

I created the `DeclarationService` and the `DeclarationApiConnector` classes and made a start on implementing the `GetAllSummaries` query. I've added `@todo` comments in the following commit https://github.com/php-twinfield/twinfield/commit/7f55c358e91b3bfefd5ffa3a9d40002d2fa125c2 which should show you what's left to do.

Let me know if this helps!

**Comment by jhjvandenbroek** [comment]
Thank you for these pointers.

However by now we've implemented our own connector (without this package). I'm not sure if I will return to this package any time in the future.
