### ISSUE TITLE
Using BrowseData with optional fields gives deprecated warnings on PHP 8.1

### ISSUE THREAD

**Issue by tomdrissen** [php-twinfield/twinfield#222]
Some fields of the BrowseColumn (label, from and to) are optional. These are `null` in the class definition. In the BrowseData request the fields are converted to XML, but this will give an deprecated warning:

`Deprecated: DOMDocument::createElement(): Passing null to parameter #2 ($value) of type string is deprecated`

Possible solution: Don't add optional fields of BrowseColumn to the DOM structure.

**Comment by rojtjo** [comment]
I've opted to cast the `null` values to string since this matches the old behavior.
Changes are included in `v3.4.0`.
