### ISSUE TITLE
wrong code

### ISSUE THREAD

**Issue by bitworkz** [php-twinfield/twinfield#30]
When i install with composer i get the old code from pronamic.

**Comment by Daanvm** [comment]
We are currently working towards a 2.0 release, but it is not completed yet. When you use composer to install this library, it will install the latest release by default.

Keep an eye on this repo, we will release the 2.0 somewhere in the upcoming weeks.

**Comment by bitworkz** [comment]
hi daan,

thanks for your answer. is the deprecated code still working?

**Comment by Daanvm** [comment]
There are a lot of fixes and improvements coming to the 2.0 release. And it's a non-backwards compatible release, so updating from a 1.x release might not be very trivial.

However, version 1.x still works in the same way as it has worked for the past few years.

**Comment by bitworkz** [comment]
hi daan, ik probeer te werken met versie 1 omdat we het dringend nodig hebben. nu als ik inlog dan denk ik dat dit wel lukt maar als ik uit onze test office alle klanten wil displayen of een klant wil aanmaken dan gebeurt er helemaal niets. zou ik hiervoor ergens wat ondersteuning kunnen krijgen?

**Comment by Daanvm** [comment]
Hi @bitworkz, we're not related to Twinfield, we're just another user of their API. I have not worked with version 1.x, so I can't really help you with that.

But did you check [the readme of the 1.x version](https://github.com/php-twinfield/twinfield/blob/release-1.0/readme.md)? The current readme is already updated for version 2.

**Comment by bitworkz** [comment]
hi daan,

i checked with twinfield about settings etcetera and all are setup properly. i followed the examples like in the version 1.x readme but i can't get it working and it seems very easy to work with so i don't understand.

**Comment by willemstuursma** [comment]
Sorry @bitworkz, we don't provide integration level support on this library.

If you have an issue in the code or a pull request, we can work from there but if you are just integrating this library you are on your own.
