### ISSUE TITLE
Unable to set vat code on Bank Transaction VAT line

### ISSUE THREAD

**Issue by Daanvm** [php-twinfield/twinfield#33]
There is currently [only a getter](https://github.com/php-twinfield/twinfield/blob/master/src/Transactions/BankTransactionLine/Vat.php#L102-L108). It needs a setter too, and must be added to the DOM Document.

**Comment by Daanvm** [comment]
Same for the `vatturnover`, `vatbaseturnover` and `vatrepturnover` fields

**Comment by willemstuursma** [comment]
np, will add
