### ISSUE TITLE
Autoload not working

### ISSUE THREAD

**Issue by babyasishhira** [php-twinfield/twinfield#36]
Hi everyone,
I downloaded this project on my local computer using composer method, and then composer made the autoload.php file.

And then include the autoload file to my php script but I am getting class not found error.

Please see my below code 

`<?php 
require_once "vendor/autoload.php";`
`$config = new \PhpTwinfield\Secure\Config();`

Error I am getting is

> 
**Fatal error: Class 'PhpTwinfield\Secure\Config' not found in C:\xampp\htdocs\twinfield\index.php on line 3**

Is your autoload not working ? Or I have some error on it ? Can you please guide me ?

**Comment by babyasishhira** [comment]
After read the autoload code I see that you have wrong information in readme.md file.

Because the class declare should be `\Pronamic\Twinfield\Secure\Config()`

**Comment by willemstuursma** [comment]
Thanks! The readme is still for 1.1 which you downloaded using composer.

We're working on 2.0 at the moment which uses the new namespace.
