### ISSUE TITLE
Documentation is very poor

### ISSUE THREAD

**Issue by anand007pandey** [php-twinfield/twinfield#37]
First of all, your work for twinfield is much appreciated. But the documentation for the php is very poor. I am still not found where the secret key for twinfield? Can you give more detailed function with proper response.  

For ex:  
```
$empsode='1002';
$customer = $customerApiConnector->get($empcode);
```

When call this i get  the error like this.

> (1/1) FatalThrowableErrorType error: Too few arguments to function PhpTwinfield\ApiConnectors\CustomerApiConnector::get(), 1 passed in C:\xampp\htdocs\twinfield\app\Http\Controllers\ApiController.php on line 90 and exactly 2 expected

Instead of this we have to pass the office object as well on this call.

```
$office = new Office();
$office->setCode($officecode);
$customerApiConnector = new \PhpTwinfield\ApiConnectors\CustomerApiConnector($login); //Get the detail of ONLY /ONE customer
$customer = $customerApiConnector->get($empcode, $office);
```

when call like this than we get the object.

 `PhpTwinfield\Customer Object
(
    [code:PhpTwinfield\Customer:private] => 1002
    [UID:PhpTwinfield\Customer:private] => 440a8044-7743-4876-9e77-d1a800378a51
    [status:PhpTwinfield\Customer:private] => active
    [name:PhpTwinfield\Customer:private] => Anand Pandey
    [type:PhpTwinfield\Customer:private] => DEB
    [inUse:PhpTwinfield\Customer:private] => false
    [behaviour:PhpTwinfield\Customer:private] => normal
    [touched:PhpTwinfield\Customer:private] => 3
    [beginPeriod:PhpTwinfield\Customer:private] => 0
    [beginYear:PhpTwinfield\Customer:private] => 0
    [endPeriod:PhpTwinfield\Customer:private] => 0
    [endYear:PhpTwinfield\Customer:private] => 0
    [website:PhpTwinfield\Customer:private] => www.demo.com
    [cocNumber:PhpTwinfield\Customer:private] => 
    [vatNumber:PhpTwinfield\Customer:private] => 
    [editDimensionName:PhpTwinfield\Customer:private] => true
    [dueDays:PhpTwinfield\Customer:private] => 30
    [payAvailable:PhpTwinfield\Customer:private] => 
    [payCode:PhpTwinfield\Customer:private] => 
    [vatCode:PhpTwinfield\Customer:private] => 
    [eBilling:PhpTwinfield\Customer:private] => 
    [eBillMail:PhpTwinfield\Customer:private] => 
    [creditManagement:PhpTwinfield\Customer:private] => PhpTwinfield\CustomerCreditManagement Object
        (
            [responsibleUser:PhpTwinfield\CustomerCreditManagement:private] => 
            [baseCreditLimit:PhpTwinfield\CustomerCreditManagement:private] => 0.00
            [sendReminder:PhpTwinfield\CustomerCreditManagement:private] => 1
            [reminderEmail:PhpTwinfield\CustomerCreditManagement:private] => 
            [blocked:PhpTwinfield\CustomerCreditManagement:private] => 
            [freeText1:PhpTwinfield\CustomerCreditManagement:private] => 
            [freeText2:PhpTwinfield\CustomerCreditManagement:private] => 007
            [freeText3:PhpTwinfield\CustomerCreditManagement:private] => 
            [comment:PhpTwinfield\CustomerCreditManagement:private] => 
        `)`
    [addresses:PhpTwinfield\Customer:private] => Array
        (
            [1] => PhpTwinfield\CustomerAddress Object
                (
                    [ID:PhpTwinfield\CustomerAddress:private] => 1
                    [type:PhpTwinfield\CustomerAddress:private] => invoice
                    [default:PhpTwinfield\CustomerAddress:private] => true
                    [name:PhpTwinfield\CustomerAddress:private] => Anand
                    [contact:PhpTwinfield\CustomerAddress:private] => 
                    [country:PhpTwinfield\CustomerAddress:private] => IN
                    [city:PhpTwinfield\CustomerAddress:private] => Indore
                    [postcode:PhpTwinfield\CustomerAddress:private] => 452001
                    [telephone:PhpTwinfield\CustomerAddress:private] => 
                    [fax:PhpTwinfield\CustomerAddress:private] => 
                    [email:PhpTwinfield\CustomerAddress:private] => anand@comfisoft.com
                    [field1:PhpTwinfield\CustomerAddress:private] => 
                    [field2:PhpTwinfield\CustomerAddress:private] => lig
                    [field3:PhpTwinfield\CustomerAddress:private] => indore
                    [field4:PhpTwinfield\CustomerAddress:private] => 
                    [field5:PhpTwinfield\CustomerAddress:private] => 
                    [field6:PhpTwinfield\CustomerAddress:private] => 
                )
        )
    [banks:PhpTwinfield\Customer:private] => Array
        (
        )
    [groups:PhpTwinfield\Customer:private] => 
    [office:PhpTwinfield\Customer:private] => PhpTwinfield\Office Object
        (
            [code:PhpTwinfield\Office:private] => NLA000068
            [countryCode:PhpTwinfield\Office:private] => 
            [name:PhpTwinfield\Office:private] => 
        )
)`

**Comment by Daanvm** [comment]
Hi @anand007pandey, it looks like you have answered your question yourself, right?

We're still working on this library. Some of the documentation is missing or outdated, because we've changed a lot the last few weeks. Keep an eye on this branch for the 2.0 release.

I'll add a warning to the current README.
