### ISSUE TITLE
Update documentation for base example

### ISSUE THREAD

**Issue by alexjeen** [php-twinfield/twinfield#38]
Existing getting started gives some errors

    $config = new \PhpTwinfield\Secure\Config();
    $config->setCredentials('username', 'password', 'enviroment', 'office code');

    // setup login
    $login = new \PhpTwinfield\Secure\Login($config);

    // get office
    $office = \PhpTwinfield\Office::fromCode('officecode');

    // get a list of all customers.
    $customerApiConnector = new \PhpTwinfield\ApiConnectors\CustomerApiConnector($login);
    $customerList = $customerApiConnector->listAll($office);

I also think you should make all office parameters optional, if it's not passed you can get the office code from the Secure/Config object (last parameter).

**Comment by willemstuursma** [comment]
> I also think you should make all office parameters optional, if it's not passed you can get the office code from the Secure/Config object (last parameter).

We are operating within an organization with multiple offices, so we want to keep the office as an explicit and required parameter to prevent reading from / writing to the wrong office. 

I'll make the code and examples more clear.

**Comment by willemstuursma** [comment]
Done in #75.
