### ISSUE TITLE
Not get the response after send new customer.

### ISSUE THREAD

**Issue by anand007pandey** [php-twinfield/twinfield#42]
Hello fellow developers,

This is the code in which i want to create the new customer and it will also create when i loggedin with twinfield account UI,  but not send the proper response that customer will create or not?
Please help me how can i do this?

Thanks in advance.

`
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;
use PhpTwinfield\Secure\Login;
use PhpTwinfield\Office;
use \PhpTwinfield\Services\LoginService;
use Exception;

public function createnewcustomer(Request $request){
        $this->validate($request, [
            'user'         => 'required',
            'password'     => 'required',
            'organisation' => 'required',
            'empcode'      => 'required',
            'name'         => 'required',
            'postalcode'   => 'required',
            'city'         => 'required',
            'country'      => 'required',
            'email'        => 'required'
        ]);
        $user     = $request->input('user');
        $password = $request->input('password');
        $org      = $request->input('organisation');
        $setcode  = $request->input('empcode');
        $name     = $request->input('name');
        $postalcode = $request->input('postalcode');
        $fax      = $request->input('fax');
        $city     = $request->input('city');
        $phone     = $request->input('telephone');
        $country  = $request->input('country');
        $email    = $request->input('email');
        $setebill = $request->input('setEBilling');
        $setebillmail = $request->input('setEBillMail');
        $setvat   = $request->input('setVatCode');
        $setduedays = $request->input('setDueDays');
        $setcocno = $request->input('setCocNumber');//It is depricated and use in address field5
        $settype = $request->input('setType');
        try
        {
            $config = new \PhpTwinfield\Secure\Config();
            $config->setCredentials($user, $password , $org , '');
            $login = new \PhpTwinfield\Secure\Login($config);
            $customerFactory = new \PhpTwinfield\ApiConnectors\CustomerApiConnector($login);
            // First, create the objects you want to send.
            
            $customer = new \PhpTwinfield\Customer();
            $customer
                ->setCode($setcode)
                ->setName($name)
                ->setType('DEB')
                ->setEBilling($setebill)
                ->setEBillMail($setebillmail)
                ->setDueDays($setduedays);
                
            $customerAddress = new \PhpTwinfield\CustomerAddress();
            $customerAddress 
                ->setType($settype)
                ->setDefault(false)
                ->setPostcode($postalcode)
                ->setCity($city)
                ->setCountry($country)
                ->setTelephone($phone)
                ->setField4($setvat)
                ->setField5($setcocno)
                ->setFax($fax)
                ->setEmail($email);
            $customer->addAddress($customerAddress);

            // And secondly, send it to Twinfield.
          $response =  $customerFactory->send($customer);
         print_r($response);
`

**Comment by alexjeen** [comment]
Try this code to get the errors from the factory that twinfield gave back (if $response == false saving in Twinfield failed):

    $tfResponse = $customerFactory->getResponse();

    foreach ($tfResponse->getErrorMessages() as $message) {
        print_r($message);
    }
    foreach ($tfResponse->getWarningMessages() as $message) {
        print_r($message)
    }
