### ISSUE TITLE
Response::isSuccessful() returns always false for Electronic Bank Statements

### ISSUE THREAD

**Issue by Daanvm** [php-twinfield/twinfield#44]
Electronic Bank Statements are sent in a batch, and the `result="1"` from the response is set on each individual bank statement:

```xml
<?xml version="1.0"?>
<statements target="electronicstatements" importduplicate="0">
    <statement target="electronicstatements" result="1">
        <!-- ... -->
    </statement>
    <!-- etc... -->
</statements>
```

The `Response::isSuccessful()` method doesn't find the `result="1"` in the root element and returns `false`. This causes an exception even though the request was successful.

Probably the best way to implement this is to verify for all `<statement />` tags that they are successful.

**Comment by willemstuursma** [comment]
Can you give me an XML response for when you send 1 item?

**Comment by Daanvm** [comment]
Looking at the code of this client, I think we never send 1 item. The `send()` method in the API Connectors just call `sendAll()`. But from the documentation I understand that in that case it's just the `<transaction>`/`<statement>`/etc element that is the root node.

However, I noticed that the response for sending transactions is inconsistent with the response for electronic bank statements:

```xml
<?xml version="1.0"?>
<transactions result="1">
    <transaction result="1" location="temporary">
        <!-- ... -->
    </transaction>
    <!-- etc... -->
</transactions>
```

Note that in this case there is also a `result` attribute on the root node. That same attribute doesn't exist in the response for electronic bank statements.
