### ISSUE TITLE
Start and close value should not be mandatory

### ISSUE THREAD

**Issue by Daanvm** [php-twinfield/twinfield#45]
The opening and closing balance for bank transactions and electronic bank statements (implemented in the `StartAndCloseValueFields` trait) should not be mandatory. From the docs:

**Electronic bank statements**
> * `startvalue`: Opening balance. If not provided, the opening balance will be based on the previous bank statement.
> * `closevalue`: Closing balance. If not provided, the closing balance will be based on the opening balance and the total amount of the transactions.

**Bank transactions**
> * `startvalue`: Opening balance. If not provided, the opening balance is set to zero.
> * `closevalue`: Closing balance. If not provided, the closing balance is set to zero.

Making these fields optional helps us by not having to keep track of the current balance for bank accounts.

There should be a separate setter for the currency, which is now set in `setStartvalue()`.

Also note that `ElectronicBankStatement::setTransactions()` and `BankTransaction::addLine()` currently require the `startvalue` or `closevalue` to be set.

**Comment by willemstuursma** [comment]
Let me know if this works for you or if you really need the ability to not send the `<startvalue>` element for BankTransfers.
