### ISSUE TITLE
Improvement make sure to honour the posting limits

### ISSUE THREAD

**Issue by alexjeen** [php-twinfield/twinfield#48]
When posting in batches to Twinfield (for instance multiple dimensions or multiple transactions). Make sure to honour it's element limitations:

https://c3.twinfield.com/webservices/documentation/#/GettingStarted/FUP

    Advise is to limit the number of children within a parent to 25. So 25 elements within a <general> element, 25 elements within e.g. a <transactions> element and so on.

They are enforcing it starting this year :) Means that you can a SOAP error when you actually go over it with a number of %.

**Comment by willemstuursma** [comment]
This will be part of the 2.0 release, see `\PhpTwinfield\ApiConnectors\ProcessXmlApiConnector::chunk()`.
