### ISSUE TITLE
Don't use WSDL_CACHE_BOTH

### ISSUE THREAD

**Issue by Daanvm** [php-twinfield/twinfield#50]
See https://bugs.php.net/bug.php?id=75065

We should use `WSDL_CACHE_MEMORY` instead in the [`BaseService` class](https://github.com/php-twinfield/twinfield/blob/master/src/Services/BaseService.php#L32).

**Comment by alexjeen** [comment]
Also, for our tests we have noticed that the following Soap Options work best for long, continued postings :)

        $this->config->setSoapClientOptions([
            'connection_timeout' => 10,
            'cache_wsdl' => WSDL_CACHE_MEMORY,
            'keep_alive' => false,
        ]);

We have done continues postings of dimensions, transactions etc of about 3 hours in test runs. Otherwise we would get some timeouts, no soap headers received etc.
