### ISSUE TITLE
Give example to add sales invoice and transactions(Purchase, Sale, Journal) 

### ISSUE THREAD

**Issue by anand007pandey** [php-twinfield/twinfield#51]
Dear Developers,

Actually it is not an issue but its my request.

Can you please add the example code for add invoice and transactions ? I have not found any example for that and i am new to twinfield, so please, please, please add some more examples like given in main page https://github.com/php-twinfield/twinfield so it will do great help to me and other newbies. Its my humble request to you.

Appreciate your work a lot. :)

**Comment by Daanvm** [comment]
Hi @anand007pandey,
We're currently still developing this library, so the documentation might not be complete or up to date. We will probably add more documentation in the future.

For invoices you would need the `Invoice` object and for transactions you would need either `BankTransaction`, `JournalTransaction`, `PurchaseTransaction` or `SalesTransaction`. It is all very similar to the `Customer` resource described in the readme.

Unfortunately we're not able to help you with integrating Twinfield. We're not related to Twinfield, we're just another user of their API. If you need help using their API you should contact Twinfield.
