### ISSUE TITLE
Sending a sales invoice returns a null response

### ISSUE THREAD

**Issue by Waterdhavian** [php-twinfield/twinfield#52]
I create a sales invoice object and send it to twinfield classic,
If i go to my twinfield classic > invoices section then i can see the invoice that i just created from laravel.
I use the code below to send my invoice.

```
$result = $invoiceApiConnector->send($invoice);
dd($result);
```

I would expect to get a complete invoice object back, according the twinfield API docs the result is an invoice object which includes the generated invoice_number which i need to generate a PDF in laravel.

Am i wrong in assuming i would get a response back?
  

This my full code, using the facade by willemo:
```
$officesApiConnector = \Twinfield::get('Office');
		
$offices = $officesApiConnector->listAll();
$office = $offices[0];
		
$customerApiConnector = \Twinfield::get('Customer');
$customer = $customerApiConnector->get('1001', $office);
		
$invoiceApiConnector = \Twinfield::get('Invoice');
		
$line = new \PhpTwinfield\InvoiceLine();
$line->setQuantity(1.00);
$line->setArticle(0);
$line->setUnitsPriceExcl(100.00);
$line->setUnits(1);
$line->setVatCode("VN");
$line->setDim1(8020);
$line->setDescription("Test");
$line->setAllowDiscountOrPremium(false);
		
$invoice = new \PhpTwinfield\Invoice();
$invoice->setCustomer($customer);
$invoice->setOffice($office);
$invoice->addLine($line);
$invoice->setStatus("concept");
$invoice->setPaymentMethod("bank");
$invoice->setInvoiceType("FACTUUR");
$invoice->setInvoiceDate("20180104");
$invoice->setCurrency("EUR");
$invoice->setBank("BNK");
$invoice->setPeriod('2018/01');
$invoice->setDueDate(\Carbon\Carbon::now()->addMonth());

// Send it to Twinfield.
$result = $invoiceApiConnector->send($invoice);
		
dd($result);
	
return view('index');
```

**Comment by willemstuursma** [comment]
`public function send(Invoice $invoice): void` is a void function and does not return anything. 

You need to use `\PhpTwinfield\ApiConnectors\InvoiceApiConnector::get()` to retrieve the invoice again.

**Comment by Waterdhavian** [comment]
```
public function get(string $code, string $invoiceNumber, Office $office)
    {
        // Make a request to read a single invoice. Set the required values
        $request_invoice = new Request\Read\Invoice();
        $request_invoice
            ->setCode($code)
            ->setNumber($invoiceNumber)
            ->setOffice($office->getCode());
 
        // Send the Request document and set the response to this instance
        $response = $this->sendDocument($request_invoice);
 
        return InvoiceMapper::map($response);
    }
```

How can i provide the invoice_number if does not get returned to me by a send?

**Comment by willemstuursma** [comment]
Right, I see the problem. 

This would require some changes. Feel free to create a PR or maybe we will get to it eventually.

**Comment by Waterdhavian** [comment]
I will see if i can fix it :)

**Comment by alexjeen** [comment]
Can you still get the response from the invoiceFactory or did you change this logic?

**Comment by Waterdhavian** [comment]
If i call a get on the InvoiceFactory with the invoice_Id as the 2nd parameter then my invoice get returned to me. I have not changed anything in this codebase yet.

**Comment by Daanvm** [comment]
The `Invoice` object is returned from `InvoiceApiConnector::send($invoice)`, or it throws an exception if the invoice could not be created.

When using the `sendAll()` method it returns an `MappedResponseCollection`. You can use it like this:

```php
$responses = $invoiceApiConnector->sendAll($invoices);

foreach ($responses as $response) {
    try {
        $invoice = $response->unwrap();
        // Invoice created successfully.
    } catch (\PhpTwinfield\Exception $e) {
        // Invoice could not be created.
    }
}
