### ISSUE TITLE
Oauth login

### ISSUE THREAD

**Issue by anand007pandey** [php-twinfield/twinfield#54]
Hi,
When i use the oauth way of signing in to twinfield i get an error. This is my code:

`public function login(\Illuminate\Http\Request $request) {
        $clientID = $request->get('clientID');
        $clientSecret = $request->get('clientSecret');
        $returnURL = $request->get('returnURL');
        $Organization = $request->get('Organization');
        $config = new \PhpTwinfield\Secure\Config();
        $config->setOAuthParameters($clientID, $clientSecret, $returnURL, $Organization, true);
        $connection = new \PhpTwinfield\Secure\Connection($config);
        $logs = new \PhpTwinfield\Services\LoginService();
        $newval = $logs->getSessionIdAndCluster($config);
        print_r($newval);
}` 

error is: **sorry, temp_token not set**

regards

**Comment by anand007pandey** [comment]
Anyone please reply me, its urgent and i need to add. Thanks...

**Comment by alexjeen** [comment]
This is not a discussion forum, also your question is vague and unanswerable.

**Comment by willemstuursma** [comment]
Please debug the integration with Twinfield yourself. If there is a bug _in this library_, you can open an issue or pull request.

**Comment by anand007pandey** [comment]
@alexjeen : First i think you are very helpful person, but you are not. Sorry to disturb you and sorry to all developer. I will find my way, thanks to all BTW.
