### ISSUE TITLE
TwinfieldReference interface

### ISSUE THREAD

**Issue by Thijs-Riezebeek** [php-twinfield/twinfield#56]
It would be nice if the library provided a `TwinfieldReference` interface that can be used when matching. Should look something like:

```php
interface TwinfieldReference
{
    public function getOffice();

    public function getCode();

    public function getNumber();

    public function getLineNumber();
}
```

**Comment by willemstuursma** [comment]
On which elements should this be implemented @Thijs-Riezebeek ?

**Comment by Thijs-Riezebeek** [comment]
Even without an implementation this would be a useful addition. If I am correct, the Matching API basically works based on 2 references, so the Matching API's methods could accept such an interface.

Besides that, I think that adding a `getReference()` on objects returned by a `send()` or `sendAll()` (for example a `BankTransactionLine` or a `ElectronicBankStatementTransaction`) will be really useful.

**Comment by willemstuursma** [comment]
It's done!
