### ISSUE TITLE
New customer not create

### ISSUE THREAD

**Issue by anand007pandey** [php-twinfield/twinfield#60]
When  i create the new customer with the given code. The error occur:

>  FatalThrowableError Call to undefined method PhpTwinfield\Customer::setType()

Seems the 'settype' method is not present in Customer.php. Please update the readme file as well, i am unable to update.

`$config = new \PhpTwinfield\Secure\Config();
$config->setCredentials($user, $password , $org , '');
$connection = new \PhpTwinfield\Secure\Connection($config);
$customer_factory = new ApiConnectors\CustomerApiConnector($connection);
// First, create the objects you want to send.
$customer = new Customer();

$customer = new \PhpTwinfield\Customer();
$customer
    ->setCode($setcode)
    ->setName($name)
    ->setType('DEB')
    ->setEBilling($setebill)
    ->setEBillMail($setebillmail)
    ->setDueDays($setduedays);
    
$customerAddress = new \PhpTwinfield\CustomerAddress();
$customerAddress 
    ->setType($settype)
    ->setDefault(false)
    ->setPostcode($postalcode)
    ->setCity($city)
    ->setCountry($country)
    ->setTelephone($phone)
    ->setField4($setvat)
    ->setField5($setcocno)
    ->setFax($fax)
    ->setEmail($email);
$customer->addAddress($customerAddress);

// And secondly, send it to Twinfield.
$customerFactory->send($customer);`

**Comment by willemstuursma** [comment]
Thanks. Type of Customer is always `DEB`. You don't have to set this on your objects.

I'll update the example.

**Comment by anand007pandey** [comment]
Hi @willemstuursma : Would you please tell me how to get response that customer is create or not from after calling this line?

`$customerFactory->send($customer);`

**Comment by willemstuursma** [comment]
@anand007pandey With the latest version, the Customer will be returned or an exception will be thrown that indicates the error.

**Comment by anand007pandey** [comment]
Ok thanks
