### ISSUE TITLE
Not getting total amount including VAT for invoice get() method

### ISSUE THREAD

**Issue by anand007pandey** [php-twinfield/twinfield#67]
I have to get the data of invoice and for this i used the code below. The invoice is 'salesinvoice' but it gives error

> (1/1) Exception
> Invoice 10120180001 of type SALESINVOICE does not exist.

`
public function getallinvoices(Request $request) {
        $user = $request->input('user');
        $password = $request->input('password');
        $org = $request->input('organisation');
        $invoicecode = $request->input('invoicecode');
        $officecode = $request->input('officecode');
        
        try {
            $config = new \PhpTwinfield\Secure\Config();
            $config->setCredentials($user, $password, $org, '');
            $office = new Office();
            $office->setCode($officecode);
            $connection = new \PhpTwinfield\Secure\Connection($config);
            $invoice = new \PhpTwinfield\ApiConnectors\InvoiceApiConnector($connection);
 
            $invresult = $invoice->get('salesinvoice',$invoicecode,$office);
            print_r($invresult);
            $jsonResponse = JsonResponse::success($invresult);
        } catch (SoapFault $e) {
            $jsonResponse = empty($e->getMessage()) ? JsonResponse::error(class_basename($e)) : JsonResponse::error($e->getMessage());
        }
        return $jsonResponse;
    }`

**Comment by willemstuursma** [comment]
> Invoice 10120180001 of type SALESINVOICE does not exist.

Are you sure this invoice exists @anand007pandey ?
