### ISSUE TITLE
Mysteriously logged out during operations

### ISSUE THREAD

**Issue by willemstuursma** [php-twinfield/twinfield#69]
We got this error a few times:

```
E_ERROR: Uncaught SoapFault exception: [soap:Client] Your logon credentials are not valid anymore. Try to log on again. in vendor/php-twinfield/twinfield/src/Services/ProcessXmlService.php:50
Stack trace:
#0 vendor/php-twinfield/twinfield/src/Services/ProcessXmlService.php(50): SoapClient->__call('ProcessXmlStrin...', Array)
#1 vendor/php-twinfield/twinfield/src/ApiConnectors/BankTransactionApiConnector.php(56): PhpTwinfield\Services\ProcessXmlService->sendDocument(Object(PhpTwinfield\DomDocuments\BankTransactionDocument))
```

For reliability, we should automate re-connecting.

**Comment by willemstuursma** [comment]
(cc @Thijs-Riezebeek)

**Comment by Daanvm** [comment]
We found out this was caused by us both using the same credentials in our scripts. As soon as @Thijs-Riezebeek started his script, my session was made invalid.

I assume this will no longer be an issue when we switch over to oauth authentication, but you know what they say about assumptions...

**Comment by willemstuursma** [comment]
Ah. I think it is still good to merge these changes, the logged in person will flip all the time but at least it will work.

**Comment by marceldecroon** [comment]
Hi. Switching to oauth will definitely solve this problem. By doing so, you don't need to login in order to open a session. All you have to do is passing the access_token as part of the request to Twinfield.
