### ISSUE TITLE
sendAll() should not stop after first error

### ISSUE THREAD

**Issue by Daanvm** [php-twinfield/twinfield#73]
When sending objects in chunks, `sendAll()` throws an exception as soon as one object in a chunk contains an error. This means that all following chunks aren't even sent to Twinfield.

Secondly, throwing an exception when one object contains an error makes it impossible to get the returned responses of the successful objects.

**Suggested solution**
When we remove the `$response->assertSuccessful()` line from `PhpTwinfield\Services\ProcessXmlService::sendDocument()`, all chucks will be processed and an array of `IndividualMappedResponse` will be returned. The `assertSuccessful()` check is only done once the response is unwrapped.

Instead of returning an array of `IndividualMappedResponse` we should return a response object with methods as `hasSuccessfulResponses()`, `countSuccessfulResponses()`, `getSuccessfulResponses()`, `hasFailedResponses()`, `countFailedResponses()`, `getFailedResponses()`, `getAllResponses()` and `assertAllSuccessful()`.

**Comment by Daanvm** [comment]
When building this, please keep in mind that both the following use cases should work easy:

1. I want to send a lot of objects to Twinfield and I don't need the returned response. I only want to know if there were any errors and if so, for which objects.
2. I want to send a lot of objects to Twinfield and I need the returned response of all successful created objects. I also want to know for which objects there was an error.

**Comment by willemstuursma** [comment]
Your suggestion sounds great. 

@mvdpanne, you should create a class that extends from `ArrayObject` that contains all `\PhpTwinfield\Response\IndividualMappedResponse` and adds the methods suggested by @Daanvm on top.

**Comment by willemstuursma** [comment]
We need to require `ext-spl` after this.

**Comment by willemstuursma** [comment]
`getAllResponses()` would not be needed, you could simply iterate over the returned collection.

**Comment by Thijs-Riezebeek** [comment]
Is there a big benefit in making ext-spl a requirement just so we can
extend ArrayObject?

It still can't be passed to native array functions and countable,
traversable, etc can easily be implemented manually, removing a dependency.

I can see the benefit of it, I'm just wondering if it's worth the
dependency.

**Comment by Daanvm** [comment]
>  I'm just wondering if it's worth the dependency.

From http://php.net/manual/en/spl.installation.php:
> This extension is available and compiled by default in PHP 5.0.0.

We already depend on PHP 7.1, and I don't see why anyone would compile a custom PHP binary without SPL installed. The dependency is not an issue in this case.

**Comment by Thijs-Riezebeek** [comment]
In that case I say go for it!
