### ISSUE TITLE
Error while sending invoice

### ISSUE THREAD

**Issue by CasNelissen** [php-twinfield/twinfield#77]
When we're trying to send an invoice, we get the following error:

"The element `unitspriceexcl` can not be supplied"

We've got the following code:

`
$customer = new Customer($config->getConfig());
$customer->setOffice(9999);

$customer = $customer->getCustomer("1001");

$invoice = new Invoice($config->getConfig());
$invoice->setOffice(9999);

$line = new InvoiceLine();
$line
    ->setQuantity(1.00)
    ->setArticle(123456789)
    ->setUnits(1)
    ->setVatCode("01SHT")
    ->setDim1(800500)
    ->setDescription("TEST")
    ->setAllowDiscountOrPremium(false)
;

$twinfieldInvoice = new TwinfieldInvoice();
$twinfieldInvoice
    ->setCustomer($customer)
    ->addLine($line)
    ->setStatus("concept")
    ->setPaymentMethod("bank")
    ->setInvoiceType("FACTUUR")
    ->setInvoiceDate((new DateTime())->format('Ymd'))
    ->setCurrency("EUR")
    ->setBank("BNK")
    ->setPeriod("2018/02")
    ->setDueDate((new DateTime())->modify("+30 days"))
;
`

Maybe it's me, but I don't see any `setUnitsPriceExcl` function call.

**Comment by Daanvm** [comment]
Hi @CasNelissen,
There should probably be a check to see if `unitspriceexcl` is empty, and if it is it should not be added to the XML that is sent to Twinfield. There is currently no such check in the `InvoicesDocument` class.

If you could create a pull request, I am more than willing to merge it!
