### ISSUE TITLE
get invoice not working

### ISSUE THREAD

**Issue by chris087** [php-twinfield/twinfield#88]
`  $invoiceApiConnector = new \PhpTwinfield\ApiConnectors\InvoiceApiConnector($connection);
  
  
  $office_code = '710030721';
  $office   = \PhpTwinfield\Office::fromCode($office_code);
  $invoicenr = 'YBHM-2018-0013';
            
  $res = $invoiceApiConnector->get('INVOICE', $invoicenr, $office);`

Result: (always), even when changing invoice nr to a fake number...

PhpTwinfield\Invoice Object
(
    [customer:PhpTwinfield\Invoice:private] => PhpTwinfield\Customer Object
        (
            [code:PhpTwinfield\Customer:private] => 
            [UID:PhpTwinfield\Customer:private] => 
            [status:PhpTwinfield\Customer:private] => 
            [name:PhpTwinfield\Customer:private] => 
            [type:PhpTwinfield\Customer:private] => DEB
            [country:PhpTwinfield\Customer:private] => 
            [inUse:PhpTwinfield\Customer:private] => 
            [behaviour:PhpTwinfield\Customer:private] => 
            [touched:PhpTwinfield\Customer:private] =>

**Comment by chris087** [comment]
via de PHP example (via Twinfield) krijg ik dit:

<read msgtype="error" msg="invoicenumber moet een geheel getal zijn." result="0">

maar als ik in Twinfield inlog... krijg ik allemaal factuurnummers als:

YBHM-2018-0013
YBHM-2018-0012
YBHM-2018-0016

Vaag...

**Comment by marceldecroon** [comment]
There is a distinct difference between invoices and transactions. An invoice number of an invoice is always a number. An invoice number of a transaction can contain also alphanumeric characters.

**Comment by chris087** [comment]
Got unpaid invoices with 

stdClass Object
(
    [SearchResult] => stdClass Object
        (
        )

    [data] => stdClass Object
        (
            [TotalRows] => 59
            [Columns] => stdClass Object
                (
                    [string] => Array
                        (
                            [0] => Factuurnr.
                            [1] => Bedrag
                            [2] => Debiteur
                            [3] => Naam
                            [4] => Debet/credit
                        )

                )

            [Items] => stdClass Object
                (
                    [ArrayOfString] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [string] => Array
                                        (
                                            [0] => 000000000806
                                            [1] => 63.50


When doing this: same result (no results..)

` $invoiceApiConnector = new \PhpTwinfield\ApiConnectors\InvoiceApiConnector($connection);

$office_code = '710030721';
$office = \PhpTwinfield\Office::fromCode($office_code);
$invoicenr = '000000000806';

$res = $invoiceApiConnector->get('INVOICE', $invoicenr, $office);`

Result: (always), even when changing invoice nr to a fake number...

PhpTwinfield\Invoice Object
(
[customer:PhpTwinfield\Invoice:private] => PhpTwinfield\Customer Object
(
[code:PhpTwinfield\Customer:private] =>
[UID:PhpTwinfield\Customer:private] =>
[status:PhpTwinfield\Customer:private] =>
[name:PhpTwinfield\Customer:private] =>
[type:PhpTwinfield\Customer:private] => DEB
[country:PhpTwinfield\Customer:private] =>
[inUse:PhpTwinfield\Customer:private] =>
[behaviour:PhpTwinfield\Customer:private] =>
[touched:PhpTwinfield\Customer:private] =>

**Comment by willemstuursma** [comment]
Hi @chris087. We're not using the invoices integration much, hence it is not as well fleshed out as other parts.

You can check the Twinfield documentation here: https://c3.twinfield.com/webservices/documentation/#/ApiReference/SalesInvoices

There are probably some changes needed to the InvoiceApiConnector, but I'll leave that to you. Once you've figured it out, a pull request would be greatly appreciated.
