### ISSUE TITLE
Delete provisional transactions

### ISSUE THREAD

**Issue by Daanvm** [php-twinfield/twinfield#89]
It is possible to delete provisional transactions with the following code:

```php
$document = new DOMDocument();
$document->loadXML(<<<XML
<transaction action="delete" reason="Test transaction">
    <office>OFFICE001</office>
    <code>BNK</code>
    <number>201700006</number>
</transaction>
XML
);
$bankTransactionApiConnector->sendXmlDocument($document);
```

I would like to see a `delete()` method directly on both the `TransactionApiConnector` and the `BankTransactionApiConnector`. Note that the reason is required, it will fail if the reason is not included.

### Result
Verification of the result works the same as when adding a new transaction, with `result` and `msg` attribute on the root element:

```xml
<?xml version="1.0"?>
<transaction action="delete" reason="Test transaction" msgtype="error" msg="De status van de boeking moet Concept zijn." result="0">
    <office>OFFICE001</office>
    <code>BNK</code>
    <number>201700006</number>
</transaction>
```

**Comment by Thijs-Riezebeek** [comment]
I'd like to point out that the `BookingReferenceInterface` should be used for such a method:

```php
public function delete(BookingReferenceInterface $bookingReference) {
    // ...
}
```
