### ISSUE TITLE
Provide `getReference()` method on transactions

### ISSUE THREAD

**Issue by Thijs-Riezebeek** [php-twinfield/twinfield#91]
Currently there is no way to get a `BookingReferenceInterface` on transactions/statements. A `getReference()` method should be added to sales transactions, bank transactions, electronic bank statements, and probably a few more objects to easily retrieve this. The method should be nullable since a `number` might not always be set on those objects.

Something like:

```php
public function getReference(): ?BookingReferenceInterface;
```

**Comment by willemstuursma** [comment]
Fixed in #92.

**Comment by willemstuursma** [comment]
> The method should be nullable since a number might not always be set on those objects.

It's not an error to get a booking reference from an uninitialized / partially initialized object?

**Comment by Thijs-Riezebeek** [comment]
It's not that it is partially initialized. The object can be fully initialized, but only once it is recreated from a Twinfield response will it contain the `number` field required to return a `BookingReferenceInterface`.

**Comment by willemstuursma** [comment]
I don't think it needs to be nullable.
