### ISSUE TITLE
Prefix invoice number

### ISSUE THREAD

**Issue by CasNelissen** [php-twinfield/twinfield#93]
Is there a possibility to add a prefix to an invoice number?

**Comment by willemstuursma** [comment]
Sorry, we're not Twinfield. You should contact Twinfield directly.

We only offer support on the code in this repository.

**Comment by CasNelissen** [comment]
This actually would help, cause Twinfield doesn't support multiple ledgers in an account. So the only option you've got is to setup an separate line of invoice numbers.

**Comment by marceldecroon** [comment]
@CasNelissen You can create multiple invoice types and set the next invoice number field with different prefixes. Note that the invoice number is a numeric field.
