### ISSUE TITLE
How to use "Browse data" to implement "paid invoices"?

### ISSUE THREAD

**Issue by tjblackheart** [php-twinfield/twinfield#99]
Hello,

this is not really an issue but an understanding question: I am trying to implement the "Paid Invoices" use case, found here: https://c3.twinfield.com/webservices/documentation/#/UseCases/PaidInvoices - would this be possible extending the Invoice Request or should I try to create a new Browse request? Could one use Transactions for that? I would be really grateful if somebody could point me into the right direction and toss some hints.

Thanks, also for your work done already.

**Comment by willemstuursma** [comment]
Hi @tjblackheart. We haven't implemented the "Browse Data" resources offered by Twinfield. 

You would need to start by adding an `ApiConnector` class for the Browse Data resource.

Then, you should add some methods to the new ApiConnector that make it more useful.

**Comment by tjblackheart** [comment]
Hi,

ok, thanks. I figured it out and created a browse document and a mapper for my use case, which works fine for now.

Thanks!

**Comment by willemstuursma** [comment]
Cool! We're very open about contributions, feel free to open a PR if you think it is useful for a greater community @tjblackheart.

**Comment by Wouter0100** [comment]
Any way you could contribute this back to the repository, @tjblackheart? Would be great - as I'm also looking to use this scenario.

**Comment by willemstuursma** [comment]
See #117 for a Browse Data implementation.

**Comment by willemstuursma** [comment]
Now available in v2.6.1.
